            ***Statistic***

    
    - mean
    - median
    - mode
    - var
    - std
    - cov
    - correlation
    - percentile - quantile
    - sum 
    - len
    -  count
    

In [2]:
import numpy as np 

dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

### Always prefer to give array for operation rather than giving as it is list.

In [3]:
arr = np.arange(1, 21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [4]:
avg = np.sum(arr) / np.size(arr)
avg

np.float64(10.5)

In [5]:
mean = np.mean(arr)
mean

np.float64(10.5)

In [18]:
median = np.median(arr)
median

np.float64(10.5)

## Variance : 
                           / sumation (x - u)²\
                 VAR  =   | -----------------  |
                           \     N            /

     - step 1. calculate the mean.
     - step 2. substract every element from mean.
     - step 3. square of all the step2 elements
     - step 4. calculate numerator sum of all the element of step 3.
     - step 5. calculate denominator i.e. size of array.
     - step 6. calculate variance i.e. numerator / denominator.

In [14]:
print("original array : ", arr)
mean  = np.mean(arr)
print("mean : ", mean)
arr2 = arr - mean
print("step 2 x - u : ", arr2)
arr3 = arr2 ** 2
print("square all : ", arr3)
Nm = np.sum(arr3)
print("summation of all (Numerator) : ", arr4)
Dm = np.size(arr)
print("N : ", Dm)
var = Nm / Dm
print("variance : ", var)

original array :  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
mean :  10.5
step 2 x - u :  [-9.5 -8.5 -7.5 -6.5 -5.5 -4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5
  4.5  5.5  6.5  7.5  8.5  9.5]
square all :  [90.25 72.25 56.25 42.25 30.25 20.25 12.25  6.25  2.25  0.25  0.25  2.25
  6.25 12.25 20.25 30.25 42.25 56.25 72.25 90.25]
summation of all (Numerator) :  665.0
N :  20
variance :  33.25


In [6]:
variance = np.var(arr)
variance

np.float64(33.25)

In [15]:
(np.sum(np.square(arr-np.mean(arr))))/np.size(arr)

np.float64(33.25)

### Co-Variance

                        cov (x, y) =  /   summation (x - mean(x))(y - mean(y)) \
                                     |   ------------------------------------   |
                                      \                  N                     /

    

In [48]:
arr1 = np.arange(10, 21)
arr2 = np.arange(20, 31)

mean_x = np.mean(arr1)
mean_y = np.mean(arr2)

A = arr1 - mean_x
B = arr2 - mean_y

arr3 = np.multiply(A , B)

Nu = np.sum(arr3)

cov = Nu / np.size(arr3)
cov


np.float64(10.0)

In [49]:
arr11 = np.arange(10, 21)
arr12 = np.arange(20, 31)

np.sum(np.multiply((arr11 - np.mean(arr11)),(arr12 - np.mean(arr12)))) / np.size(arr11)

np.float64(10.0)

In [50]:
A = np.arange(10, 21)
B = np.arange(20, 31)
cov_x_y = np.cov(A, B)
cov_x_y

array([[11., 11.],
       [11., 11.]])

## Standard deviation :
                          __________________________________
                         | 
                         |        var()
                        \|

In [22]:
o = np.array([1, 2, 3])
t = np.array([1, 2, 3])

o * t

array([1, 4, 9])

### distance between two points : 

a = [10, 20], 
b = [15, 19]


In [52]:
p1 = [20, 30]
p2 = [100, 130]

p1 = np.array(p1)
p2 = np.array(p2)


np.sqrt(np.sum((p1 - p2)**2))


np.float64(128.06248474865697)

In [54]:
from numpy.linalg import norm


p1 = np.array(p1)
p2 = np.array(p2)


norm(p1-p2)


np.float64(128.06248474865697)