In [ ]:
cosine similarity formula : 



SyntaxError: invalid syntax (1923229599.py, line 1)

### ***Sklearn***

    - Imputer 

        KNN Imputer 


- Before we are taking the average of the data 

In [3]:
import numpy as np 
import pandas as pd 
from sklearn.impute import KNNImputer

X = [
    [1, 2, np.nan],
    [3, np.nan, 3],
    [np.nan, 60, 5], 
    [8, 8, 7]
]

df = pd.DataFrame(X)

df

0     1    2
0  1.0   2.0  NaN
1  3.0   NaN  3.0
2  NaN  60.0  5.0
3  8.0   8.0  7.0

In [7]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import KNNImputer
#    package module          class 

In [ ]:
df

0     1    2
0  1.0   2.0  NaN
1  3.0   NaN  3.0
2  NaN  60.0  5.0
3  8.0   8.0  7.0

In [16]:
knn = KNNImputer()
knn.fit_transform(df[[0]])

array([[1.],
       [3.],
       [4.],
       [8.]])

In [17]:
ss = StandardScaler()
ss.fit_transform(df[[0]])

array([[-1.01904933],
       [-0.33968311],
       [        nan],
       [ 1.35873244]])

In [18]:
df

0     1    2
0  1.0   2.0  NaN
1  3.0   NaN  3.0
2  NaN  60.0  5.0
3  8.0   8.0  7.0

In [20]:
knn.fit_transform(df).astype(int)

array([[ 1,  2,  5],
       [ 3, 23,  3],
       [ 4, 60,  5],
       [ 8,  8,  7]])