In [1]:
# Problem-1:
# From the raw data below create a Pandas Series 'Amit', 'Bob', 'Kate', 'A', 'b', np.nan, 'Car', 'dog', 'cat'
# a) Print all elements in lower case
# b) Print all the elements in upper case
# c) Print the length of all the elements

import pandas as pd
import numpy as np 

lst = ['Amit', 'Bob', 'Kate', 'A', 'b', np.nan, 'Car', 'dog', 'cat']
s = pd.Series(lst)
print("series is : \n" ,s)
print("---------------------------------------------------")
print("lower case : ")
lower = pd.Series([v.lower() if isinstance(v, str) else v for v in s ])
for i in lower :
    print("\t", i)
print("---------------------------------------------------")
print("lower case : ")
upper = pd.Series([v.upper() if isinstance(v, str) else v for v in s ])
for i in upper :
    print("\t", i)
print("---------------------------------------------------")
print("length of the each element of the series : ")
for val in s : 
    if isinstance(val, str):
        print(len(val))
    else :
        print(val)
    

series is : 
 0    Amit
1     Bob
2    Kate
3       A
4       b
5     NaN
6     Car
7     dog
8     cat
dtype: str
---------------------------------------------------
lower case : 
	 amit
	 bob
	 kate
	 a
	 b
	 nan
	 car
	 dog
	 cat
---------------------------------------------------
lower case : 
	 AMIT
	 BOB
	 KATE
	 A
	 B
	 nan
	 CAR
	 DOG
	 CAT
---------------------------------------------------
length of the each element of the series : 
4
3
4
1
1
nan
3
3
3


In [ ]:
# 6.2: From the raw data below create a Pandas Series 
# ' Atul', 'John ', ' jack', 'Sam'
# a) Print all elements after stripping spaces from the left and right
# b) Print all the elements after removing spaces from the left only
# c) Print all the elements after removing spaces from the right only

True

In [26]:
s2 = pd.Series([" Atul", "John ", " jack", "Sam"])
for v in s2 :
    if type(v) == str : 
        print(f"\t{v.strip()}")
    else :
        print(v)

	Atul
	John
	jack
	Sam


In [27]:
s2 = pd.Series([" Atul", "John ", " jack", "Sam"])
for v in s2 :
    if type(v) == str : 
        print(f"\t{v.lstrip()}")
    else :
        print(v)

	Atul
	John 
	jack
	Sam


In [28]:
s2 = pd.Series([" Atul", "John ", " jack", "Sam"])
for v in s2 :
    if type(v) == str : 
        print(f"\t{v.rstrip()}")
    else :
        print(v)

	 Atul
	John
	 jack
	Sam


In [ ]:
import pandas as pd
s = pd.Series(6, index = range(0, 6))
s

ValueError: Length of values (2) does not match length of index (6)

In [11]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
np.split(arr1, 9)

[array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([8]),
 array([9])]

In [ ]:
it can split anyone from the given matrix ---------