# To use numpy for your operations first you have to import numpy like -

In [2]:
import numpy as np

## Creating a numpy array name "arr"

+ using arange() method we can get a 1 d array of range as input (start, end(exclusive), step) 
+ and then using .reshape(row, col) we reshape that array "arr" into 2 D array

In [3]:
arr = np.arange(1, 17).reshape(4,4)

### Some of the operations of numpy to get its characteristics 

        + like --> 
                    1. arr.size        :        gives total no element present inside the array arr
                    2. arr.shape       :        provide what shape it contains 
                    3. arr.ndim        :        returns the dimension of the array arr
                    4. arr.dtype       :        gives data type of the element of array arr
                    5. arr.itemsize    :        gives size of elements inside the numpy array

In [4]:
print(f"original array is {arr}\n\n\nand size of array is : {arr.size}")

original array is [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


and size of array is : 16


In [5]:
print(f"shape of arr is : {arr.shape}")

shape of arr is : (4, 4)


In [6]:
print(f"dimension of the arr array is arr.ndim : {arr.ndim}")

dimension of the arr array is arr.ndim : 2


In [7]:
print(f"data type of the arr array is arr.dtype : {arr.dtype}")

data type of the arr array is arr.dtype : int64


In [8]:
# this will return the size of the element into the bytes.

print(f"itemsize of the arr array is arr.itemsize : {arr.itemsize}")

itemsize of the arr array is arr.itemsize : 8


### Types of Array : 

+ Can create different type of array using : 
                    
                    --> 1. zeroes 
                        2. ones
                        3. full(customize)
                        4. eye(digonal ones/ identity matrix)
                        5. range based(arange())
                        6. evenly spased (linspace(start, end, parts))

In [9]:
zero_arr = np.zeros((3, 3))
print(f"zero array is : \n{zero_arr}")

zero array is : 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
ones = np.ones((2, 4), dtype=int)
print(f"ones array is : \n{ones}")

ones array is : 
[[1 1 1 1]
 [1 1 1 1]]


In [65]:
identity = np.eye(3, 3, k=0 ,dtype=int)
print(f"identity matrix array is :\n \n{identity}")

identity matrix array is :
 
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [12]:
full = np.full((2, 2), "hey")
print(f"full array is : \n\n\n{full}")

full array is : 


[['hey' 'hey']
 ['hey' 'hey']]


In [13]:
arr_range = np.arange(1, 10)
print(f"range array is : \n{arr_range}")

range array is : 
[1 2 3 4 5 6 7 8 9]


In [14]:
print(arr_range.reshape((3, 3)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
evenSpace = np.linspace(1, 10, 5, True, True, int)
print(f"evenly spaced from 1 to 10 with 5 values of array is : \n{evenSpace}")

evenly spaced from 1 to 10 with 5 values of array is : 
(array([ 1,  3,  5,  7, 10]), np.float64(2.25))


## Slicing and Indexing : 

+ Slicing : 

            - in numpy slicing, slicing only provide the view of the original array. 

            - And do not give copy, so if anything changes into the original array then it will be reflecting on slice too.

            + while copy is something which does not share memory, means it will not gonna change if something change in the original array  after copy.

In [16]:
print(f"array we have is : \n\n{arr}")

array we have is : 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [17]:
print(f"slice of 2nd column remember its start from index 0 array is :\n \n{arr[:, 2]}")

slice of 2nd column remember its start from index 0 array is :
 
[ 3  7 11 15]


In [18]:
print(f"slice of 2nd row and 3rd column remember its start from index 0 array is :\n \n{arr[2, 3]}")

slice of 2nd row and 3rd column remember its start from index 0 array is :
 
12


In [19]:
print(f"slice of 2nd column remember its start from index 0 array is :\n \n{arr[:, 2]}")

slice of 2nd column remember its start from index 0 array is :
 
[ 3  7 11 15]


In [20]:
print(f"array we have is : \n\n{arr}\n\n")

print(f"slice of 1st to 3rd(exclclusive) row and 2nd to 4th(exclusive) column  remember its start from index 0 array is :\n \n{arr[1:3,2:4 ]}")

array we have is : 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


slice of 1st to 3rd(exclclusive) row and 2nd to 4th(exclusive) column  remember its start from index 0 array is :
 
[[ 7  8]
 [11 12]]


### Copy vs View (Critical Concept)

            📌 View shares memory, copy doesn’t.

In [21]:
a = np.array([1,2,3])
b = a.view()
c = a.copy()

a[0] = 100
print(b)
print(c)

[100   2   3]
[1 2 3]


## Broadcasting (Why NumPy is Powerful)
            - Broadcasting allows NumPy to perform operations on arrays of different shapes.

In [23]:
arr2 = np.arange(1, 5)
print(f"array 2 is : \n\n{arr2}\n\n array 2 if multiply with 2 then (arr2 * 2) : \n\n\n{arr2 * [3, 5, 1, 2]}")



array 2 is : 

[1 2 3 4]

 array 2 if multiply with 2 then (arr2 * 2) : 


[ 3 10  3  8]


In [24]:
arr2 = arr2.reshape((2, 2))
print(f"new reshaped(2, 2) arr2 is : \n\n{arr2}\n\nand its multiplication or any other operation does the same effect : \n\n{arr2*10}")

new reshaped(2, 2) arr2 is : 

[[1 2]
 [3 4]]

and its multiplication or any other operation does the same effect : 

[[10 20]
 [30 40]]


#### if you are giving single elemnt into broadcasting then it will do operation into each elements into the array else if youre giving some list structure to do operations that should be the same shape as numpy array else it will throw error

In [26]:
print(f"array 2 is : \n\n{arr2}\n\n array 2 if multiply with 2 then (arr2 * 2) : \n\n\n{arr2 * [3, 5, 2]}")


ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

### Mathematical Operations (Vectorized)

In [ ]:
a = np.arange(1, 6)

b = np.arange(6, 11)

print(f"array a & b is \n\na : {a}\n\nb : {b}")

array a & b is 

a : [1 2 3 4 5]

b : [ 6  7  8  9 10]


##### Operations : 

                    1. addition a + b
                    2. substraction a - b
                    3. multiplication a * b
                    4. division a // b 
                    5. power a ** 2
            

In [28]:
print(f"array a & b is \n\na : {a}\n\nb : {b}\n\naddition is : {a+b}")

array a & b is 

a : [1 2 3 4 5]

b : [ 6  7  8  9 10]

addition is : [ 7  9 11 13 15]


In [29]:
print(f"array a & b is \n\na : {a}\n\nb : {b}\n\nsubstraction is  : {a -b}")

array a & b is 

a : [1 2 3 4 5]

b : [ 6  7  8  9 10]

substraction is  : [-5 -5 -5 -5 -5]


In [32]:
print(f"array a & b is \n\na : {a}\n\nb : {b}\n\ndivision is b // a : {b//a}")


array a & b is 

a : [1 2 3 4 5]

b : [ 6  7  8  9 10]

division is b // a : [6 3 2 2 2]


In [38]:
print(f"array a & b is \n\na : {a}\n\nb : {b}\n\ndivision is    b / a          : {b / a}")

array a & b is 

a : [1 2 3 4 5]

b : [ 6  7  8  9 10]

division is    b / a          : [6.         3.5        2.66666667 2.25       2.        ]


In [ ]:
print(f"array a & b is \n\na : {a}\n\n b : {b}\n\nmultiplication is a x b : {a * b}")

array a & b is 

a : [1 2 3 4 5]

b : [ 6  7  8  9 10]

multiplication is a x b : [ 6 14 24 36 50]


In [40]:
print(f"array a & b is \n\na : {a}\n\nb : {b}\n\na raise to the power 2 : {a ** 2}\n\nb raise to the power 2 : {b ** 2}")

array a & b is 

a : [1 2 3 4 5]

b : [ 6  7  8  9 10]

a raise to the power 2 : [ 1  4  9 16 25]

b raise to the power 2 : [ 36  49  64  81 100]


### universal Functions : 

                            1. np.sqrt(array)
                            2. np.log(array)
                            3. np.exp(array)
                            4. np.sin(array)
                            

In [47]:
sqrt_of_b = np.sqrt(b)

print(f"square root of the array b of each element is : {sqrt_of_b}")

square root of the array b of each element is : [2.44948974 2.64575131 2.82842712 3.         3.16227766]


In [48]:
log_of_b = np.log(b)

print(f"log  of the array b of each element is : {log_of_b}")

log  of the array b of each element is : [1.79175947 1.94591015 2.07944154 2.19722458 2.30258509]


In [ ]:
exp_of_b = np.exp(b)
print(f"exp the array b of each element is : {exp_of_b}")

exp the array b of each element is : [  403.42879349  1096.63315843  2980.95798704  8103.08392758
 22026.46579481]


## Aggregation Functions : 

            --> like 

                    1. np.sum(arr)	    -->     Total sum
                    2. np.mean(arr)	    -->     Average
                    3. np.max(arr)	    -->     Max
                    4. np.min(arr)	    -->     Min
                    5. np.std(arr)	    -->     Standard deviation

In [50]:
print(f"new reshaped(2, 2) arr2 is : \n\n{arr2}")

new reshaped(2, 2) arr2 is : 

[[1 2]
 [3 4]]


In [51]:
sum_of_arr2 = np.sum(arr2)

print(f"new reshaped(2, 2) arr2 is : \n\n{arr2}\n\nand the sum of all elements is : {sum_of_arr2}")

new reshaped(2, 2) arr2 is : 

[[1 2]
 [3 4]]

and the sum of all elements is : 10


In [52]:
sum_col_wise = np.sum(arr2, axis=0)
print(f"new reshaped(2, 2) arr2 is : \n\n{arr2}\n\nand the sum of all elements Column wise is : {sum_col_wise}")

new reshaped(2, 2) arr2 is : 

[[1 2]
 [3 4]]

and the sum of all elements Column wise is : [4 6]


In [55]:
sum_row_wise = np.sum(arr2, axis=1)
print(f"new reshaped(2, 2) arr2 is : \n\n{arr2}\n\nand the sum of all elements Row wise is : {sum_row_wise}")

new reshaped(2, 2) arr2 is : 

[[1 2]
 [3 4]]

and the sum of all elements Row wise is : [3 7]


+ mean of array 


In [58]:
mean = np.mean(arr2)
print(f"new reshaped(2, 2) arr2 is : \n\n{arr2}\n\nand the mean of all elements is : {mean}")

new reshaped(2, 2) arr2 is : 

[[1 2]
 [3 4]]

and the mean of all elements is : 2.5


In [61]:
mean_Col_wise = np.mean(arr2, axis=0, dtype=int)
print(f"new reshaped(2, 2) arr2 is : \n\n{arr2}\n\nand the mean of elements Column wise is : {mean_Col_wise}")

new reshaped(2, 2) arr2 is : 

[[1 2]
 [3 4]]

and the mean of elements Column wise is : [2 3]


In [63]:
mean_row_wise = np.mean(arr2, axis=1, dtype=float)
print(f"new reshaped(2, 2) arr2 is : \n\n{arr2}\n\nand the mean of elements row wise is : {mean_row_wise}")

new reshaped(2, 2) arr2 is : 

[[1 2]
 [3 4]]

and the mean of elements row wise is : [1.5 3.5]


+ max and min 

In [66]:
maxi = np.max(arr2)
mini = np.min(arr2)

print(f"new reshaped(2, 2) arr2 is : \n\n{arr2}\n\nand minimum elements is : {mini}\n\nand maximum element is : {maxi}")

new reshaped(2, 2) arr2 is : 

[[1 2]
 [3 4]]

and minimum elements is : 1

and maximum element is : 4


In [68]:
maxi_row_wise = np.max(arr2, axis=1)
mini_row_wise = np.min(arr2, axis=1)

print(f"new reshaped(2, 2) arr2 is : \n\n{arr2}\n\nand minimum elements in each row is : {mini_row_wise}\n\nand maximum element in each row is : {maxi_row_wise}")

new reshaped(2, 2) arr2 is : 

[[1 2]
 [3 4]]

and minimum elements in each row is : [1 3]

and maximum element in each row is : [2 4]


In [72]:
maxi_col_wise = np.max(arr2, axis=0)
mini_col_wise = np.min(arr2, axis=0)

print(f"new reshaped(2, 2) arr2 is : \n\n{arr2}\n\nand minimum elements in each col is : {mini_col_wise}\n\nand maximum element in each col is : {maxi_col_wise}")

new reshaped(2, 2) arr2 is : 

[[1 2]
 [3 4]]

and minimum elements in each col is : [1 2]

and maximum element in each col is : [3 4]


## Flattening an array (multidimension) : 

                    + flattining an multidimensional array means converting a array into 1-D array.

In [3]:
arr3 = np.arange(1, 10).reshape((3, 3))
print(f"3-D array we recently formed is : \n\n{arr3}")

flat_array = arr3.flatten()
print(f"\nand now the flatten array is : {flat_array}\n\n and original array after (arr3.flatten()) function : is unchanged\n\n {arr3}")

3-D array we recently formed is : 

[[1 2 3]
 [4 5 6]
 [7 8 9]]

and now the flatten array is : [1 2 3 4 5 6 7 8 9]

 and original array after (arr3.flatten()) function : is unchanged

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


### Axis Concept



In [5]:

np.sum(arr3, axis=0)


# Column-wise


array([12, 15, 18])

In [6]:

np.sum(arr3, axis=1)


# Row-wise

array([ 6, 15, 24])

### Boolean Indexing (Filtering Data)

                    + we just need to write condition inside the [] brackets to filter data

In [11]:
arr5 = np.array([10,20,30,40])
print(f"after filtering the data greater than 20 in array : {arr5[arr5 > 20]}")

# 📌 Core for data cleaning.

after filtering the data greater than 20 in array : [30 40]


### + Fancy Indexing : 

                    - it is a way to access multiple index at the same time. 

In [ ]:
index = [0, 2] 
print("element at index [0, 2] is arr5[index] OR arr5[[0, 1]] : ", arr5[index], " OR ", arr5[[0, 2]])

element at index [0, 2] is arr5[index] OR arr5[[0, 1]] :  [10 30]  OR  [10 30]


In [33]:
print("array is : \n\n", arr)

print("\n\nelement at index [0, 2] is arr[index] : \n\n", arr[index], " \n\nOR arr[[0, 2]]\n\n ", arr[[0, 2]], "\n\n")

array is : 

 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


element at index [0, 2] is arr[index] : 

 [[ 1  2  3  4]
 [ 9 10 11 12]]  

OR arr[[0, 2]]

  [[ 1  2  3  4]
 [ 9 10 11 12]] 




In [32]:
print("array is : \n\n", arr)

print("\n\nelement at index [0, 2] is arr[index] : \n\n", arr[index], " \n\nOR arr[[1, 2], [0, 2]]\n\n ", arr[[1, 2], [0, 2]], "\n\n")

array is : 

 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


element at index [0, 2] is arr[index] : 

 [[ 1  2  3  4]
 [ 9 10 11 12]]  

OR arr[[1, 2], [0, 2]]

  [ 5 11] 




###  📌 Sorting & Searching : 

                            - sorting of an ndarry using sort method. np.sort(arrayName, axis)

                            + meanwhile 

                            - searching using filtering and where () 

In [58]:
arr6 = np.array([[8, 35, 2], [76, 43, -1], [12, 6, -3]])
print("arr6 is\n\n", arr6)
sor = arr6.sort(axis=0, kind='heap')
sort = np.sort(arr6, axis= 1)
print("\nsorted array is : \n\n", sor)
print("\nsorted array is : \n\n", arr6)
print("\n np sort array is : \n\n", sort)

np.argsort(arr6)

arr6 is

 [[ 8 35  2]
 [76 43 -1]
 [12  6 -3]]

sorted array is : 

 None

sorted array is : 

 [[ 8  6 -3]
 [12 35 -1]
 [76 43  2]]

 np sort array is : 

 [[-3  6  8]
 [-1 12 35]
 [ 2 43 76]]


array([[2, 1, 0],
       [2, 0, 1],
       [2, 1, 0]])

In [63]:
where = np.where(arr6 > 10)
arr6[where]

array([12, 35, 76, 43])

In [68]:
arr6[np.where(arr6 < 10)], type(arr6[np.where(arr6 < 10)])

(array([ 8,  6, -3, -1,  2]), numpy.ndarray)

In [ ]:
def placeColor(board, row) : 

    if row == len(board) :
        count+=1
        return 
    for i in range(3) : 
        if isredSafe() :
            placeColor(board, row+1)


count = 0
n = int(input())
board = []
# board = [[0]*3]*n
# board = [[0 for i in range(3)]for i in range(n)]
for i in range(n) :
    row = []
    for j in range(3) :
        row += [0]
    board += [row]



[[0, 0, 0], [0, 0, 0]]

In [79]:
[2, 3, 4] + [[5, 4]]

[2, 3, 4, [5, 4]]

In [80]:
l  = [[1, 2, 4], [1, 23, 5]]

[1, 2, 4] in l

True

TypeError: 'numpy.ndarray' object is not callable