# Numpy :
        - Numerical python or Number python  is used for math operation.
        - Generally Elements provieded in following formats or types.

                + Lists
                + tuples
                + array 
                + tensors


        -  List and Tuples are basic level representatitons with no shape and dimensions.
        -  Math operations are slow with List and Tuples.
        -  Numpy arrays are having shapes and dimensions.
        -  Numpy arrays and Tensors are both same in nature.
        -  When CPU is there Numpy arrays are enough to perform the operations.
        -  When GPU is there tensors are required to perform the operations.
        

In [10]:
import numpy as np
import sys

In [11]:
sys.version

'3.12.9 (tags/v3.12.9:fdb8142, Feb  4 2025, 15:27:58) [MSC v.1942 64 bit (AMD64)]'

In [12]:
np.__version__

'2.4.1'

In [13]:
# Creating array
array = np.array([1,2,3,4,1,2,3,4,])
array

array([1, 2, 3, 4, 1, 2, 3, 4])

In [14]:
type(array)
# N - Dimensional array

numpy.ndarray

+ **Why Numpy**

In [15]:
l1 = [10, 20, 30, 40]
l2 = [100, 200, 300, 400]

ans = []

i = 0 
j = 0 

while i < len(l1) and j < len(l2) :
    ans.append(l1[i] + l2[j])
    l1[i] += l2[j]
    i += 1
    j += 1

l1, ans

([110, 220, 330, 440], [110, 220, 330, 440])

In [16]:
array = np.array(l1)
array2 = np.array(l2)

In [17]:
l1*l2

TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
array * array2

array([ 11000,  44000,  99000, 176000])

In [ ]:
l1 / l2

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [ ]:
array / array2

array([1.1, 1.1, 1.1, 1.1])

In [ ]:
l1 - l2

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [ ]:
array2 - array2

array([0, 0, 0, 0])

In [ ]:
l2

[100, 200, 300, 400]

In [ ]:
array2

array([100, 200, 300, 400])

In [ ]:
l1

[110, 220, 330, 440]

In [ ]:
array

array([110, 220, 330, 440])

In [ ]:
array + array2

array([210, 420, 630, 840])

+ **Speed Test**

In [26]:
import time
start = time.time()
l1 = list(range(1, 100000))
l2 = list(range(1, 100000))
l3 = [i*j for i,j in zip(l1, l2)]
end = time.time()
print(f"time : {end - start}")

time : 0.029514312744140625


In [27]:
import time
start = time.time()
arr1 = np.arange(1, 100000)
arr2 = np.arange(1, 100000)
arr3 = arr1 * arr2
end = time.time()
print(f"time : {end - start}")

time : 0.021376371383666992
